#!/usr/bin/env python3

"""Generate the C++ and Rust refresh-probe workload constants."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tomllib


ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = Path(__file__).with_name("spec.toml")
CPP_PATH = ROOT / "reference" / "probe_config.h"
RUST_PATH = ROOT / "panel" / "probe_config.rs"

SCALARS = (
    ("version", "SPEC_VERSION"),
    ("cpu_hz", "CPU_HZ"),
    ("width", "WIDTH"),
    ("height", "HEIGHT"),
    ("refresh_interval_ms", "REFRESH_INTERVAL_MS"),
    ("partial_samples", "PARTIAL_SAMPLES"),
    ("partial_profile_samples", "PARTIAL_PROFILE_SAMPLES"),
    ("partial_span_samples", "PARTIAL_SPAN_SAMPLES"),
    ("full_performance_samples", "FULL_PERFORMANCE_SAMPLES"),
    ("full_profile_samples", "FULL_PROFILE_SAMPLES"),
    ("full_soak_cycles", "FULL_SOAK_CYCLES"),
    ("reference_cold_partial_samples", "REFERENCE_COLD_PARTIAL_SAMPLES"),
    ("reference_gray_partial_contract_samples", "REFERENCE_GRAY_PARTIAL_CONTRACT_SAMPLES"),
    ("reference_gray_full_samples", "REFERENCE_GRAY_FULL_SAMPLES"),
    ("band_width", "BAND_WIDTH"),
    ("marker_scale", "MARKER_SCALE"),
    ("marker_digits", "MARKER_DIGITS"),
    ("digit_width", "DIGIT_WIDTH"),
    ("digit_height", "DIGIT_HEIGHT"),
    ("marker_padding", "MARKER_PADDING"),
    ("gray_band_height", "GRAY_BAND_HEIGHT"),
    ("gray_checker_tile", "GRAY_CHECKER_TILE"),
    ("gray_expected_fnv1a", "GRAY_EXPECTED_FNV1A"),
)


def load_spec() -> dict[str, object]:
    with SPEC_PATH.open("rb") as source:
        spec = tomllib.load(source)
    rows = spec["digit_rows"]
    if len(rows) != 10 or any(len(row) != spec["digit_height"] for row in rows):
        raise ValueError("digit_rows must contain ten digit_height-sized rows")
    if spec["gray_band_height"] * 3 != spec["height"]:
        raise ValueError("gray_band_height must divide the screen into thirds")
    partial_scan_rows = spec["partial_scan_rows"]
    if not partial_scan_rows or any(
        not 1 <= int(scan_rows) <= int(spec["height"])
        for scan_rows in partial_scan_rows
    ):
        raise ValueError("partial_scan_rows must contain values in 1..=height")
    if list(partial_scan_rows) != sorted(set(partial_scan_rows)):
        raise ValueError("partial_scan_rows must be unique and ascending")
    return spec


def cpp_value(name: str, value: int) -> str:
    if name == "GRAY_EXPECTED_FNV1A":
        return f"0x{value:08x}U"
    return f"{value}U"


def render_cpp(spec: dict[str, object]) -> str:
    constants = "\n".join(
        f"constexpr uint32_t k{name.title().replace('_', '')} = {cpp_value(name, int(spec[key]))};"
        for key, name in SCALARS
    )
    rows = ",\n".join(
        "    {" + ", ".join(f"0b{int(value):05b}" for value in row) + "}"
        for row in spec["digit_rows"]
    )
    partial_scan_rows = ", ".join(str(int(value)) for value in spec["partial_scan_rows"])
    return f"""// Generated by ../common/generate.py from ../common/spec.toml. Do not edit.
#pragma once

#include <stdint.h>

namespace RefreshProbeConfig
{{
{constants}

constexpr uint8_t kDigitRows[10][kDigitHeight] = {{
{rows},
}};
constexpr uint32_t kPartialScanRows[] = {{{partial_scan_rows}}};
}} // namespace RefreshProbeConfig
"""


def render_rust(spec: dict[str, object]) -> str:
    constants = "\n".join(
        f"pub const {name}: u32 = {int(spec[key]):#010x};"
        if name == "GRAY_EXPECTED_FNV1A"
        else f"pub const {name}: u32 = {int(spec[key])};"
        for key, name in SCALARS
    )
    rows = ",\n".join(
        "    [\n        " + ", ".join(f"0b{int(value):05b}" for value in row) + ",\n    ]"
        for row in spec["digit_rows"]
    )
    partial_scan_rows = ", ".join(str(int(value)) for value in spec["partial_scan_rows"])
    return f"""// Generated by ../common/generate.py from ../common/spec.toml. Do not edit.
#![allow(dead_code)]

{constants}

pub const DIGIT_ROWS: [[u8; DIGIT_HEIGHT as usize]; 10] = [
{rows},
];
pub const PARTIAL_SCAN_ROWS: [usize; {len(spec["partial_scan_rows"])}] = [{partial_scan_rows}];
"""


def update(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text() if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"stale generated file: {path.relative_to(ROOT)}", file=sys.stderr)
        return False
    path.write_text(content)
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    spec = load_spec()
    valid = update(CPP_PATH, render_cpp(spec), args.check)
    valid &= update(RUST_PATH, render_rust(spec), args.check)
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
