// Generated by ../common/generate.py from ../common/spec.toml. Do not edit.
#pragma once

#include <stdint.h>

namespace RefreshProbeConfig
{
constexpr uint32_t kSpecVersion = 1U;
constexpr uint32_t kCpuHz = 240000000U;
constexpr uint32_t kWidth = 600U;
constexpr uint32_t kHeight = 600U;
constexpr uint32_t kRefreshIntervalMs = 250U;
constexpr uint32_t kPartialSamples = 100U;
constexpr uint32_t kPartialProfileSamples = 20U;
constexpr uint32_t kPartialSpanSamples = 20U;
constexpr uint32_t kFullPerformanceSamples = 100U;
constexpr uint32_t kFullProfileSamples = 20U;
constexpr uint32_t kFullSoakCycles = 500U;
constexpr uint32_t kReferenceColdPartialSamples = 5U;
constexpr uint32_t kReferenceGrayPartialContractSamples = 20U;
constexpr uint32_t kReferenceGrayFullSamples = 5U;
constexpr uint32_t kBandWidth = 50U;
constexpr uint32_t kMarkerScale = 14U;
constexpr uint32_t kMarkerDigits = 3U;
constexpr uint32_t kDigitWidth = 5U;
constexpr uint32_t kDigitHeight = 7U;
constexpr uint32_t kMarkerPadding = 16U;
constexpr uint32_t kGrayBandHeight = 200U;
constexpr uint32_t kGrayCheckerTile = 25U;
constexpr uint32_t kGrayExpectedFnv1A = 0x19d5b489U;

constexpr uint8_t kDigitRows[10][kDigitHeight] = {
    {0b01110, 0b10001, 0b10011, 0b10101, 0b11001, 0b10001, 0b01110},
    {0b00100, 0b01100, 0b00100, 0b00100, 0b00100, 0b00100, 0b01110},
    {0b01110, 0b10001, 0b00001, 0b00010, 0b00100, 0b01000, 0b11111},
    {0b11110, 0b00001, 0b00001, 0b01110, 0b00001, 0b00001, 0b11110},
    {0b00010, 0b00110, 0b01010, 0b10010, 0b11111, 0b00010, 0b00010},
    {0b11111, 0b10000, 0b10000, 0b11110, 0b00001, 0b00001, 0b11110},
    {0b01110, 0b10000, 0b10000, 0b11110, 0b10001, 0b10001, 0b01110},
    {0b11111, 0b00001, 0b00010, 0b00100, 0b01000, 0b01000, 0b01000},
    {0b01110, 0b10001, 0b10001, 0b01110, 0b10001, 0b10001, 0b01110},
    {0b01110, 0b10001, 0b10001, 0b01111, 0b00001, 0b00001, 0b01110},
};
constexpr uint32_t kPartialScanRows[] = {60, 300, 600};
} // namespace RefreshProbeConfig
