pub(crate) fn snapshot() -> Snapshot {
    let upload_http_ipv4_raw = UPLOAD_HTTP_IPV4.load(Ordering::Relaxed);
    let upload_http_ipv4 = if upload_http_ipv4_raw == 0 {
        None
    } else {
        Some(upload_http_ipv4_raw.to_be_bytes())
    };
    Snapshot {
        wifi_connect_attempts: WIFI_CONNECT_ATTEMPTS.load(Ordering::Relaxed),
        wifi_connect_successes: WIFI_CONNECT_SUCCESSES.load(Ordering::Relaxed),
        wifi_connect_failures: WIFI_CONNECT_FAILURES.load(Ordering::Relaxed),
        wifi_reason_no_ap_found: WIFI_REASON_NO_AP_FOUND.load(Ordering::Relaxed),
        wifi_scan_runs: WIFI_SCAN_RUNS.load(Ordering::Relaxed),
        wifi_scan_empty: WIFI_SCAN_EMPTY.load(Ordering::Relaxed),
        wifi_scan_target_hits: WIFI_SCAN_TARGET_HITS.load(Ordering::Relaxed),
        wifi_connected_watchdog_disconnects: WIFI_CONNECTED_WATCHDOG_DISCONNECTS
            .load(Ordering::Relaxed),
        wifi_reassoc_mode_pauses: WIFI_REASSOC_MODE_PAUSES.load(Ordering::Relaxed),
        wifi_reassoc_mode_resumes: WIFI_REASSOC_MODE_RESUMES.load(Ordering::Relaxed),
        wifi_reassoc_credentials_received: WIFI_REASSOC_CREDENTIALS_RECEIVED
            .load(Ordering::Relaxed),
        wifi_reassoc_credentials_changed: WIFI_REASSOC_CREDENTIALS_CHANGED.load(Ordering::Relaxed),
        wifi_reassoc_config_applied: WIFI_REASSOC_CONFIG_APPLIED.load(Ordering::Relaxed),
        wifi_reassoc_start_ok: WIFI_REASSOC_START_OK.load(Ordering::Relaxed),
        wifi_reassoc_start_err: WIFI_REASSOC_START_ERR.load(Ordering::Relaxed),
        wifi_reassoc_connect_begin: WIFI_REASSOC_CONNECT_BEGIN.load(Ordering::Relaxed),
        wifi_reassoc_connect_success: WIFI_REASSOC_CONNECT_SUCCESS.load(Ordering::Relaxed),
        wifi_reassoc_connect_failure: WIFI_REASSOC_CONNECT_FAILURE.load(Ordering::Relaxed),
        wifi_reassoc_disconnect_events: WIFI_REASSOC_DISCONNECT_EVENTS.load(Ordering::Relaxed),
        wifi_reassoc_channel_probes: WIFI_REASSOC_CHANNEL_PROBES.load(Ordering::Relaxed),
        wifi_reassoc_auth_rotations: WIFI_REASSOC_AUTH_ROTATIONS.load(Ordering::Relaxed),
        wifi_reassoc_hint_retries: WIFI_REASSOC_HINT_RETRIES.load(Ordering::Relaxed),
        wifi_reassoc_connect_ms_total: WIFI_REASSOC_CONNECT_MS_TOTAL.load(Ordering::Relaxed),
        wifi_reassoc_connect_ms_max: WIFI_REASSOC_CONNECT_MS_MAX.load(Ordering::Relaxed),
        wifi_reassoc_scan_active_runs: WIFI_REASSOC_SCAN_ACTIVE_RUNS.load(Ordering::Relaxed),
        wifi_reassoc_scan_active_empty: WIFI_REASSOC_SCAN_ACTIVE_EMPTY.load(Ordering::Relaxed),
        wifi_reassoc_scan_active_hits: WIFI_REASSOC_SCAN_ACTIVE_HITS.load(Ordering::Relaxed),
        wifi_reassoc_scan_active_ms_total: WIFI_REASSOC_SCAN_ACTIVE_MS_TOTAL
            .load(Ordering::Relaxed),
        wifi_reassoc_scan_active_ms_max: WIFI_REASSOC_SCAN_ACTIVE_MS_MAX.load(Ordering::Relaxed),
        wifi_reassoc_scan_passive_runs: WIFI_REASSOC_SCAN_PASSIVE_RUNS.load(Ordering::Relaxed),
        wifi_reassoc_scan_passive_empty: WIFI_REASSOC_SCAN_PASSIVE_EMPTY.load(Ordering::Relaxed),
        wifi_reassoc_scan_passive_hits: WIFI_REASSOC_SCAN_PASSIVE_HITS.load(Ordering::Relaxed),
        wifi_reassoc_scan_passive_ms_total: WIFI_REASSOC_SCAN_PASSIVE_MS_TOTAL
            .load(Ordering::Relaxed),
        wifi_reassoc_scan_passive_ms_max: WIFI_REASSOC_SCAN_PASSIVE_MS_MAX.load(Ordering::Relaxed),
        wifi_reassoc_reason_2: WIFI_REASSOC_REASON_2.load(Ordering::Relaxed),
        wifi_reassoc_reason_201: WIFI_REASSOC_REASON_201.load(Ordering::Relaxed),
        wifi_reassoc_reason_202: WIFI_REASSOC_REASON_202.load(Ordering::Relaxed),
        wifi_reassoc_reason_203: WIFI_REASSOC_REASON_203.load(Ordering::Relaxed),
        wifi_reassoc_reason_204: WIFI_REASSOC_REASON_204.load(Ordering::Relaxed),
        wifi_reassoc_reason_205: WIFI_REASSOC_REASON_205.load(Ordering::Relaxed),
        wifi_reassoc_reason_210: WIFI_REASSOC_REASON_210.load(Ordering::Relaxed),
        wifi_reassoc_reason_211: WIFI_REASSOC_REASON_211.load(Ordering::Relaxed),
        wifi_reassoc_reason_212: WIFI_REASSOC_REASON_212.load(Ordering::Relaxed),
        wifi_reassoc_reason_other: WIFI_REASSOC_REASON_OTHER.load(Ordering::Relaxed),
        wifi_reassoc_last_reason: WIFI_REASSOC_LAST_REASON.load(Ordering::Relaxed) as u8,
        wifi_reassoc_last_auth_idx: WIFI_REASSOC_LAST_AUTH_IDX.load(Ordering::Relaxed) as u8,
        wifi_reassoc_last_channel_hint: WIFI_REASSOC_LAST_CHANNEL_HINT.load(Ordering::Relaxed)
            as u8,
        wifi_reassoc_last_probe_idx: WIFI_REASSOC_LAST_PROBE_IDX.load(Ordering::Relaxed) as u8,
        wifi_reassoc_last_scan_channel: WIFI_REASSOC_LAST_SCAN_CHANNEL.load(Ordering::Relaxed)
            as u8,
        wifi_reassoc_last_stage: WIFI_REASSOC_LAST_STAGE.load(Ordering::Relaxed) as u8,
        upload_http_accepts: UPLOAD_HTTP_ACCEPTS.load(Ordering::Relaxed),
        upload_http_accept_errors: UPLOAD_HTTP_ACCEPT_ERRORS.load(Ordering::Relaxed),
        upload_http_accept_link_resets: UPLOAD_HTTP_ACCEPT_LINK_RESETS.load(Ordering::Relaxed),
        upload_http_request_errors: UPLOAD_HTTP_REQUEST_ERRORS.load(Ordering::Relaxed),
        upload_http_header_timeouts: UPLOAD_HTTP_HEADER_TIMEOUTS.load(Ordering::Relaxed),
        upload_http_read_body_errors: UPLOAD_HTTP_READ_BODY_ERRORS.load(Ordering::Relaxed),
        upload_http_sd_busy_errors: UPLOAD_HTTP_SD_BUSY_ERRORS.load(Ordering::Relaxed),
        upload_http_health_requests: UPLOAD_HTTP_HEALTH_REQUESTS.load(Ordering::Relaxed),
        upload_http_upload_requests: UPLOAD_HTTP_UPLOAD_REQUESTS.load(Ordering::Relaxed),
        upload_http_upload_bytes: UPLOAD_HTTP_UPLOAD_BYTES.load(Ordering::Relaxed),
        upload_http_upload_body_read_ms_total: UPLOAD_HTTP_UPLOAD_BODY_READ_MS_TOTAL
            .load(Ordering::Relaxed),
        upload_http_upload_body_read_ms_max: UPLOAD_HTTP_UPLOAD_BODY_READ_MS_MAX
            .load(Ordering::Relaxed),
        upload_http_upload_sd_wait_ms_total: UPLOAD_HTTP_UPLOAD_SD_WAIT_MS_TOTAL
            .load(Ordering::Relaxed),
        upload_http_upload_sd_wait_ms_max: UPLOAD_HTTP_UPLOAD_SD_WAIT_MS_MAX
            .load(Ordering::Relaxed),
        upload_http_upload_request_ms_total: UPLOAD_HTTP_UPLOAD_REQUEST_MS_TOTAL
            .load(Ordering::Relaxed),
        upload_http_upload_request_ms_max: UPLOAD_HTTP_UPLOAD_REQUEST_MS_MAX
            .load(Ordering::Relaxed),
        net_pipeline_dhcp_wait_count: NET_PIPELINE_DHCP_WAIT_COUNT.load(Ordering::Relaxed),
        net_pipeline_dhcp_wait_ms_total: NET_PIPELINE_DHCP_WAIT_MS_TOTAL.load(Ordering::Relaxed),
        net_pipeline_dhcp_wait_ms_max: NET_PIPELINE_DHCP_WAIT_MS_MAX.load(Ordering::Relaxed),
        net_pipeline_dhcp_ready_count: NET_PIPELINE_DHCP_READY_COUNT.load(Ordering::Relaxed),
        net_pipeline_gate_wifi_down: NET_PIPELINE_GATE_WIFI_DOWN.load(Ordering::Relaxed),
        net_pipeline_gate_link_down: NET_PIPELINE_GATE_LINK_DOWN.load(Ordering::Relaxed),
        net_pipeline_gate_no_ipv4: NET_PIPELINE_GATE_NO_IPV4.load(Ordering::Relaxed),
        net_pipeline_listener_on: NET_PIPELINE_LISTENER_ON.load(Ordering::Relaxed),
        net_pipeline_listener_off: NET_PIPELINE_LISTENER_OFF.load(Ordering::Relaxed),
        net_pipeline_accept_wait_count: NET_PIPELINE_ACCEPT_WAIT_COUNT.load(Ordering::Relaxed),
        net_pipeline_accept_wait_ms_total: NET_PIPELINE_ACCEPT_WAIT_MS_TOTAL
            .load(Ordering::Relaxed),
        net_pipeline_accept_wait_ms_max: NET_PIPELINE_ACCEPT_WAIT_MS_MAX.load(Ordering::Relaxed),
        sd_upload_errors: SD_UPLOAD_ERRORS.load(Ordering::Relaxed),
        sd_upload_busy: SD_UPLOAD_BUSY.load(Ordering::Relaxed),
        sd_upload_timeouts: SD_UPLOAD_TIMEOUTS.load(Ordering::Relaxed),
        sd_upload_power_on_failed: SD_UPLOAD_POWER_ON_FAILED.load(Ordering::Relaxed),
        sd_upload_init_failed: SD_UPLOAD_INIT_FAILED.load(Ordering::Relaxed),
        sd_upload_session_timeout_aborts: SD_UPLOAD_SESSION_TIMEOUT_ABORTS.load(Ordering::Relaxed),
        sd_upload_session_mode_off_aborts: SD_UPLOAD_SESSION_MODE_OFF_ABORTS
            .load(Ordering::Relaxed),
        sd_upload_rtt_begin_count: SD_UPLOAD_RTT_BEGIN_COUNT.load(Ordering::Relaxed),
        sd_upload_rtt_begin_ms_total: SD_UPLOAD_RTT_BEGIN_MS_TOTAL.load(Ordering::Relaxed),
        sd_upload_rtt_begin_ms_max: SD_UPLOAD_RTT_BEGIN_MS_MAX.load(Ordering::Relaxed),
        sd_upload_rtt_chunk_count: SD_UPLOAD_RTT_CHUNK_COUNT.load(Ordering::Relaxed),
        sd_upload_rtt_chunk_ms_total: SD_UPLOAD_RTT_CHUNK_MS_TOTAL.load(Ordering::Relaxed),
        sd_upload_rtt_chunk_ms_max: SD_UPLOAD_RTT_CHUNK_MS_MAX.load(Ordering::Relaxed),
        sd_upload_rtt_commit_count: SD_UPLOAD_RTT_COMMIT_COUNT.load(Ordering::Relaxed),
        sd_upload_rtt_commit_ms_total: SD_UPLOAD_RTT_COMMIT_MS_TOTAL.load(Ordering::Relaxed),
        sd_upload_rtt_commit_ms_max: SD_UPLOAD_RTT_COMMIT_MS_MAX.load(Ordering::Relaxed),
        sd_upload_rtt_abort_count: SD_UPLOAD_RTT_ABORT_COUNT.load(Ordering::Relaxed),
        sd_upload_rtt_abort_ms_total: SD_UPLOAD_RTT_ABORT_MS_TOTAL.load(Ordering::Relaxed),
        sd_upload_rtt_abort_ms_max: SD_UPLOAD_RTT_ABORT_MS_MAX.load(Ordering::Relaxed),
        sd_upload_rtt_mkdir_count: SD_UPLOAD_RTT_MKDIR_COUNT.load(Ordering::Relaxed),
        sd_upload_rtt_mkdir_ms_total: SD_UPLOAD_RTT_MKDIR_MS_TOTAL.load(Ordering::Relaxed),
        sd_upload_rtt_mkdir_ms_max: SD_UPLOAD_RTT_MKDIR_MS_MAX.load(Ordering::Relaxed),
        sd_upload_rtt_remove_count: SD_UPLOAD_RTT_REMOVE_COUNT.load(Ordering::Relaxed),
        sd_upload_rtt_remove_ms_total: SD_UPLOAD_RTT_REMOVE_MS_TOTAL.load(Ordering::Relaxed),
        sd_upload_rtt_remove_ms_max: SD_UPLOAD_RTT_REMOVE_MS_MAX.load(Ordering::Relaxed),
        boot_reset_reason_code: BOOT_RESET_REASON_CODE.load(Ordering::Relaxed) as u8,
        wifi_link_connected: WIFI_LINK_CONNECTED.load(Ordering::Relaxed),
        upload_http_listening: UPLOAD_HTTP_LISTENING.load(Ordering::Relaxed),
        upload_http_ipv4,
    }
}
