#[derive(Clone, Copy)]
#[cfg(feature = "asset-upload-http")]
pub(crate) enum SdUploadRoundtripPhase {
    Begin,
    Chunk,
    Commit,
    Abort,
    Mkdir,
    Remove,
}

#[derive(Clone, Copy)]
#[cfg(feature = "asset-upload-http")]
pub(crate) enum WifiScanPhase {
    Active,
    Passive,
}

#[derive(Clone, Copy, PartialEq, Eq)]
#[cfg(feature = "asset-upload-http")]
pub(crate) enum NetPipelineGate {
    WifiDown,
    LinkDown,
    NoIpv4,
}

#[derive(Clone, Copy)]
#[cfg(feature = "asset-upload-http")]
pub(crate) struct UploadHttpPhaseMetrics {
    pub(crate) bytes: u32,
    pub(crate) body_read_ms: u32,
    pub(crate) payload_copy_ms: u32,
    pub(crate) sd_queue_ms: u32,
    pub(crate) sd_task_wait_ms: u32,
    pub(crate) commit_ms: u32,
    pub(crate) chunk_p50_ms: u32,
    pub(crate) chunk_p95_ms: u32,
    pub(crate) chunk_max_ms: u32,
    pub(crate) chunk_samples: u32,
    pub(crate) chunk_samples_dropped: u32,
    pub(crate) sd_wait_ms: u32,
    pub(crate) request_ms: u32,
}

#[derive(Clone, Copy)]
pub(crate) struct Snapshot {
    pub(crate) wifi_connect_attempts: u32,
    pub(crate) wifi_connect_successes: u32,
    pub(crate) wifi_connect_failures: u32,
    pub(crate) wifi_reason_no_ap_found: u32,
    pub(crate) wifi_scan_runs: u32,
    pub(crate) wifi_scan_empty: u32,
    pub(crate) wifi_scan_target_hits: u32,
    pub(crate) wifi_connected_watchdog_disconnects: u32,
    pub(crate) wifi_reassoc_mode_pauses: u32,
    pub(crate) wifi_reassoc_mode_resumes: u32,
    pub(crate) wifi_reassoc_credentials_received: u32,
    pub(crate) wifi_reassoc_credentials_changed: u32,
    pub(crate) wifi_reassoc_config_applied: u32,
    pub(crate) wifi_reassoc_start_ok: u32,
    pub(crate) wifi_reassoc_start_err: u32,
    pub(crate) wifi_reassoc_connect_begin: u32,
    pub(crate) wifi_reassoc_connect_success: u32,
    pub(crate) wifi_reassoc_connect_failure: u32,
    pub(crate) wifi_reassoc_disconnect_events: u32,
    pub(crate) wifi_reassoc_channel_probes: u32,
    pub(crate) wifi_reassoc_auth_rotations: u32,
    pub(crate) wifi_reassoc_hint_retries: u32,
    pub(crate) wifi_reassoc_connect_ms_total: u32,
    pub(crate) wifi_reassoc_connect_ms_max: u32,
    pub(crate) wifi_reassoc_scan_active_runs: u32,
    pub(crate) wifi_reassoc_scan_active_empty: u32,
    pub(crate) wifi_reassoc_scan_active_hits: u32,
    pub(crate) wifi_reassoc_scan_active_ms_total: u32,
    pub(crate) wifi_reassoc_scan_active_ms_max: u32,
    pub(crate) wifi_reassoc_scan_passive_runs: u32,
    pub(crate) wifi_reassoc_scan_passive_empty: u32,
    pub(crate) wifi_reassoc_scan_passive_hits: u32,
    pub(crate) wifi_reassoc_scan_passive_ms_total: u32,
    pub(crate) wifi_reassoc_scan_passive_ms_max: u32,
    pub(crate) wifi_reassoc_reason_2: u32,
    pub(crate) wifi_reassoc_reason_201: u32,
    pub(crate) wifi_reassoc_reason_202: u32,
    pub(crate) wifi_reassoc_reason_203: u32,
    pub(crate) wifi_reassoc_reason_204: u32,
    pub(crate) wifi_reassoc_reason_205: u32,
    pub(crate) wifi_reassoc_reason_210: u32,
    pub(crate) wifi_reassoc_reason_211: u32,
    pub(crate) wifi_reassoc_reason_212: u32,
    pub(crate) wifi_reassoc_reason_other: u32,
    pub(crate) wifi_reassoc_last_reason: u8,
    pub(crate) wifi_reassoc_last_auth_idx: u8,
    pub(crate) wifi_reassoc_last_channel_hint: u8,
    pub(crate) wifi_reassoc_last_probe_idx: u8,
    pub(crate) wifi_reassoc_last_scan_channel: u8,
    pub(crate) wifi_reassoc_last_stage: u8,
    pub(crate) upload_http_accepts: u32,
    pub(crate) upload_http_accept_errors: u32,
    pub(crate) upload_http_accept_link_resets: u32,
    pub(crate) upload_http_request_errors: u32,
    pub(crate) upload_http_header_timeouts: u32,
    pub(crate) upload_http_read_body_errors: u32,
    pub(crate) upload_http_read_body_resets: u32,
    pub(crate) upload_http_sd_busy_errors: u32,
    pub(crate) upload_http_health_requests: u32,
    pub(crate) upload_http_upload_requests: u32,
    pub(crate) upload_http_upload_bytes: u32,
    pub(crate) upload_http_upload_body_read_ms_total: u32,
    pub(crate) upload_http_upload_body_read_ms_max: u32,
    pub(crate) upload_http_upload_payload_copy_ms_total: u32,
    pub(crate) upload_http_upload_payload_copy_ms_max: u32,
    pub(crate) upload_http_upload_sd_queue_ms_total: u32,
    pub(crate) upload_http_upload_sd_queue_ms_max: u32,
    pub(crate) upload_http_upload_sd_task_wait_ms_total: u32,
    pub(crate) upload_http_upload_sd_task_wait_ms_max: u32,
    pub(crate) upload_http_upload_commit_ms_total: u32,
    pub(crate) upload_http_upload_commit_ms_max: u32,
    pub(crate) upload_http_upload_chunk_p50_ms_max: u32,
    pub(crate) upload_http_upload_chunk_p95_ms_max: u32,
    pub(crate) upload_http_upload_chunk_max_ms_max: u32,
    pub(crate) upload_http_upload_chunk_samples_total: u32,
    pub(crate) upload_http_upload_chunk_samples_dropped: u32,
    pub(crate) upload_http_upload_sd_wait_ms_total: u32,
    pub(crate) upload_http_upload_sd_wait_ms_max: u32,
    pub(crate) upload_http_upload_request_ms_total: u32,
    pub(crate) upload_http_upload_request_ms_max: u32,
    pub(crate) net_pipeline_dhcp_wait_count: u32,
    pub(crate) net_pipeline_dhcp_wait_ms_total: u32,
    pub(crate) net_pipeline_dhcp_wait_ms_max: u32,
    pub(crate) net_pipeline_dhcp_ready_count: u32,
    pub(crate) net_pipeline_gate_wifi_down: u32,
    pub(crate) net_pipeline_gate_link_down: u32,
    pub(crate) net_pipeline_gate_no_ipv4: u32,
    pub(crate) net_pipeline_listener_on: u32,
    pub(crate) net_pipeline_listener_off: u32,
    pub(crate) net_pipeline_accept_wait_count: u32,
    pub(crate) net_pipeline_accept_wait_ms_total: u32,
    pub(crate) net_pipeline_accept_wait_ms_max: u32,
    pub(crate) net_pipeline_accept_arm_gap_count: u32,
    pub(crate) net_pipeline_accept_arm_gap_us_total: u32,
    pub(crate) net_pipeline_accept_arm_gap_us_max: u32,
    pub(crate) net_pipeline_accept_arm_gap_after_mkdir_count: u32,
    pub(crate) net_pipeline_accept_arm_gap_after_mkdir_us_total: u32,
    pub(crate) net_pipeline_accept_arm_gap_after_mkdir_us_max: u32,
    pub(crate) sd_upload_errors: u32,
    pub(crate) sd_upload_busy: u32,
    pub(crate) sd_upload_timeouts: u32,
    pub(crate) sd_upload_power_on_failed: u32,
    pub(crate) sd_upload_init_failed: u32,
    pub(crate) sd_upload_session_timeout_aborts: u32,
    pub(crate) sd_upload_session_mode_off_aborts: u32,
    pub(crate) sd_upload_rtt_begin_count: u32,
    pub(crate) sd_upload_rtt_begin_ms_total: u32,
    pub(crate) sd_upload_rtt_begin_ms_max: u32,
    pub(crate) sd_upload_rtt_chunk_count: u32,
    pub(crate) sd_upload_rtt_chunk_ms_total: u32,
    pub(crate) sd_upload_rtt_chunk_ms_max: u32,
    pub(crate) sd_upload_rtt_commit_count: u32,
    pub(crate) sd_upload_rtt_commit_ms_total: u32,
    pub(crate) sd_upload_rtt_commit_ms_max: u32,
    pub(crate) sd_upload_rtt_abort_count: u32,
    pub(crate) sd_upload_rtt_abort_ms_total: u32,
    pub(crate) sd_upload_rtt_abort_ms_max: u32,
    pub(crate) sd_upload_rtt_mkdir_count: u32,
    pub(crate) sd_upload_rtt_mkdir_ms_total: u32,
    pub(crate) sd_upload_rtt_mkdir_ms_max: u32,
    pub(crate) sd_upload_rtt_remove_count: u32,
    pub(crate) sd_upload_rtt_remove_ms_total: u32,
    pub(crate) sd_upload_rtt_remove_ms_max: u32,
    pub(crate) boot_reset_reason_code: u8,
    pub(crate) wifi_link_rssi_last_dbm: i32,
    pub(crate) wifi_link_rssi_min_dbm: i32,
    pub(crate) wifi_link_rssi_max_dbm: i32,
    pub(crate) wifi_link_rssi_samples: u32,
    pub(crate) wifi_link_rssi_low_samples: u32,
    pub(crate) wifi_link_connected: bool,
    pub(crate) upload_http_listening: bool,
    pub(crate) upload_http_ipv4: Option<[u8; 4]>,
}
