// Generated by ../common/generate.py from ../common/spec.toml. Do not edit.
#![allow(dead_code)]

pub const SPEC_VERSION: u32 = 1;
pub const CPU_HZ: u32 = 240000000;
pub const WIDTH: u32 = 600;
pub const HEIGHT: u32 = 600;
pub const REFRESH_INTERVAL_MS: u32 = 250;
pub const PARTIAL_SAMPLES: u32 = 100;
pub const PARTIAL_PROFILE_SAMPLES: u32 = 20;
pub const PARTIAL_SPAN_SAMPLES: u32 = 20;
pub const FULL_PERFORMANCE_SAMPLES: u32 = 100;
pub const FULL_PROFILE_SAMPLES: u32 = 20;
pub const FULL_SOAK_CYCLES: u32 = 500;
pub const REFERENCE_COLD_PARTIAL_SAMPLES: u32 = 5;
pub const REFERENCE_GRAY_PARTIAL_CONTRACT_SAMPLES: u32 = 20;
pub const REFERENCE_GRAY_FULL_SAMPLES: u32 = 5;
pub const BAND_WIDTH: u32 = 50;
pub const MARKER_SCALE: u32 = 14;
pub const MARKER_DIGITS: u32 = 3;
pub const DIGIT_WIDTH: u32 = 5;
pub const DIGIT_HEIGHT: u32 = 7;
pub const MARKER_PADDING: u32 = 16;
pub const GRAY_BAND_HEIGHT: u32 = 200;
pub const GRAY_CHECKER_TILE: u32 = 25;
pub const GRAY_EXPECTED_FNV1A: u32 = 0x19d5b489;

pub const DIGIT_ROWS: [[u8; DIGIT_HEIGHT as usize]; 10] = [
    [
        0b01110, 0b10001, 0b10011, 0b10101, 0b11001, 0b10001, 0b01110,
    ],
    [
        0b00100, 0b01100, 0b00100, 0b00100, 0b00100, 0b00100, 0b01110,
    ],
    [
        0b01110, 0b10001, 0b00001, 0b00010, 0b00100, 0b01000, 0b11111,
    ],
    [
        0b11110, 0b00001, 0b00001, 0b01110, 0b00001, 0b00001, 0b11110,
    ],
    [
        0b00010, 0b00110, 0b01010, 0b10010, 0b11111, 0b00010, 0b00010,
    ],
    [
        0b11111, 0b10000, 0b10000, 0b11110, 0b00001, 0b00001, 0b11110,
    ],
    [
        0b01110, 0b10000, 0b10000, 0b11110, 0b10001, 0b10001, 0b01110,
    ],
    [
        0b11111, 0b00001, 0b00010, 0b00100, 0b01000, 0b01000, 0b01000,
    ],
    [
        0b01110, 0b10001, 0b10001, 0b01110, 0b10001, 0b10001, 0b01110,
    ],
    [
        0b01110, 0b10001, 0b10001, 0b01111, 0b00001, 0b00001, 0b01110,
    ],
];
pub const PARTIAL_SCAN_ROWS: [usize; 3] = [60, 300, 600];
