#[derive(Clone, Copy)]
pub(crate) struct TapTraceSample {
    pub(crate) t_ms: u64,
    pub(crate) tap_src: u8,
    pub(crate) seq_count: u8,
    pub(crate) tap_candidate: u8,
    pub(crate) cand_src: u8,
    pub(crate) state_id: u8,
    pub(crate) reject_reason: u8,
    pub(crate) candidate_score: u16,
    pub(crate) window_ms: u16,
    pub(crate) cooldown_active: u8,
    pub(crate) jerk_l1: i32,
    pub(crate) motion_veto: u8,
    pub(crate) gyro_l1: i32,
    pub(crate) int1: u8,
    pub(crate) int2: u8,
    pub(crate) power_good: i16,
    pub(crate) battery_percent: i16,
    pub(crate) gx: i16,
    pub(crate) gy: i16,
    pub(crate) gz: i16,
    pub(crate) ax: i16,
    pub(crate) ay: i16,
    pub(crate) az: i16,
}
