[package]
name = "esp_idf_wifi_control_rust"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "esp_idf_wifi_control_rust"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[dependencies]
anyhow = "1.0"
log = "0.4"
esp-idf-svc = "0.51"

[build-dependencies]
embuild = "0.33"

[package.metadata.esp-idf-sys]
esp_idf_tools_install_dir = "fromenv"
