// Generated by tools/font_probe/render_specimens.py; selected session only.
pub const SLIDES: &[(&str, &str)] = &[
    (
        "roboto-inkplate-caption-w400-b1-t128",
        "/assets/spec/EDB281B1.BIN",
    ),
    (
        "literata-inkplate-caption-w400-b1-t128",
        "/assets/spec/25DFF01B.BIN",
    ),
    (
        "sourcesans3-inkplate-caption-w400-b1-t128",
        "/assets/spec/3CA5AD87.BIN",
    ),
    (
        "roboto-inkplate-caption-w400-b3-t128",
        "/assets/spec/C3C2FE04.BIN",
    ),
    (
        "literata-inkplate-caption-w400-b3-t128",
        "/assets/spec/F356BC17.BIN",
    ),
    (
        "sourcesans3-inkplate-caption-w400-b3-t128",
        "/assets/spec/BE5ED831.BIN",
    ),
];
