[package]
name = "http-upload"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[lib]

[features]
default = []
asset-upload-http-pipeline = []
host-tests = ["embassy-time/std", "sdcard/host-tests"]

[dependencies]
embassy-time = "0.5.1"
sdcard = { path = "../../storage/sdcard" }
embassy-net = { version = "0.9.1", features = ["tcp", "medium-ethernet", "proto-ipv4"] }
embassy-futures = "0.1.2"
embedded-io-async = "0.7.0"
