use core::sync::atomic::{AtomicUsize, Ordering};

#[path = "scan_process_wrap_diag/capture.rs"]
mod capture;
#[path = "scan_process_wrap_diag/logging.rs"]
mod logging;
#[path = "scan_process_wrap_diag/state.rs"]
mod state;
#[path = "scan_process_wrap_diag/wrappers.rs"]
mod wrappers;

const SLOT_COUNT: usize = 20;
const SCAN_START_ARG3_BYTES: usize = 16;

#[derive(Copy, Clone)]
struct Snapshot {
    fn_id: u8,
    args: [u32; 4],
    ret: u32,
    pre_obj_ptr: u32,
    pre_obj_word0: u32,
    pre_obj_byte8: u8,
    pre_obj_byte9: u8,
    pre_obj_word12: u32,
    pre_obj_word16: u32,
    pre_obj_word20: u32,
    pre_obj_word24: u32,
    pre_obj_byte28: u8,
    pre_obj_word32: u32,
    pre_obj_word36: u32,
    pre_obj_byte40: u8,
    pre_ptr16_word0: u32,
    pre_ptr16_word4: u32,
    pre_ptr16_word8: u32,
    pre_ptr16_word12: u32,
    pre_cmd_ptr: u32,
    pre_cmd_word0: u32,
    pre_cmd_word4: u32,
    pre_cmd_byte8: u8,
    pre_cmd_byte9: u8,
    pre_cmd_word12: u32,
    pre_cmd_word16: u32,
    pre_cmd_word20: u32,
    pre_cmd_word24: u32,
    pre_cmd_byte28: u8,
    pre_cmd_half32: u16,
    pre_cmd_word36: u32,
    pre_cmd_word40: u32,
    obj_ptr: u32,
    obj_word0: u32,
    obj_word4: u32,
    obj_byte8: u8,
    obj_byte9: u8,
    obj_word12: u32,
    obj_word16: u32,
    obj_word20: u32,
    obj_word24: u32,
    obj_byte28: u8,
    obj_word32: u32,
    obj_word36: u32,
    obj_byte40: u8,
    ptr4_word0: u32,
    ptr4_word4: u32,
    ptr4_word8: u32,
    ptr4_word12: u32,
    ptr16_word0: u32,
    ptr16_word4: u32,
    ptr16_word8: u32,
    ptr16_word12: u32,
    cmd_ptr: u32,
    cmd_word0: u32,
    cmd_word4: u32,
    cmd_byte8: u8,
    cmd_byte9: u8,
    cmd_word12: u32,
    cmd_word16: u32,
    cmd_word20: u32,
    cmd_word24: u32,
    cmd_byte28: u8,
    cmd_half32: u16,
    cmd_word36: u32,
    cmd_word40: u32,
    scan_start_pre_arg3: [u8; SCAN_START_ARG3_BYTES],
    scan_start_post_arg3: [u8; SCAN_START_ARG3_BYTES],
    scan_start_pre_op_chan: u8,
    scan_start_post_op_chan: u8,
    scan_start_pre_current_chan: u8,
    scan_start_post_current_chan: u8,
    scan_start_pre_home_chan: u8,
    scan_start_post_home_chan: u8,
    scan_start_pre_scan_word00: u32,
    scan_start_post_scan_word00: u32,
    scan_start_pre_scan_word114: u32,
    scan_start_post_scan_word114: u32,
    scan_start_pre_scan_ptr: u32,
    scan_start_post_scan_ptr: u32,
    scan_start_pre_chm_ptr: u32,
    scan_start_post_chm_ptr: u32,
    scan_start_pre_chm_ptr08: u32,
    scan_start_post_chm_ptr08: u32,
    scan_start_pre_chm_ptr0c: u32,
    scan_start_post_chm_ptr0c: u32,
    scan_get_id_exec_count: u32,
    scan_get_id_last_callback_ptr: u32,
    scan_get_id_last_arg_ptr: u32,
    scan_get_id_op_chan: u8,
    scan_get_id_scan_word114: u32,
}

impl Snapshot {
    const ZERO: Self = Self {
        fn_id: 0,
        args: [0; 4],
        ret: 0,
        pre_obj_ptr: 0,
        pre_obj_word0: 0,
        pre_obj_byte8: 0,
        pre_obj_byte9: 0,
        pre_obj_word12: 0,
        pre_obj_word16: 0,
        pre_obj_word20: 0,
        pre_obj_word24: 0,
        pre_obj_byte28: 0,
        pre_obj_word32: 0,
        pre_obj_word36: 0,
        pre_obj_byte40: 0,
        pre_ptr16_word0: 0,
        pre_ptr16_word4: 0,
        pre_ptr16_word8: 0,
        pre_ptr16_word12: 0,
        pre_cmd_ptr: 0,
        pre_cmd_word0: 0,
        pre_cmd_word4: 0,
        pre_cmd_byte8: 0,
        pre_cmd_byte9: 0,
        pre_cmd_word12: 0,
        pre_cmd_word16: 0,
        pre_cmd_word20: 0,
        pre_cmd_word24: 0,
        pre_cmd_byte28: 0,
        pre_cmd_half32: 0,
        pre_cmd_word36: 0,
        pre_cmd_word40: 0,
        obj_ptr: 0,
        obj_word0: 0,
        obj_word4: 0,
        obj_byte8: 0,
        obj_byte9: 0,
        obj_word12: 0,
        obj_word16: 0,
        obj_word20: 0,
        obj_word24: 0,
        obj_byte28: 0,
        obj_word32: 0,
        obj_word36: 0,
        obj_byte40: 0,
        ptr4_word0: 0,
        ptr4_word4: 0,
        ptr4_word8: 0,
        ptr4_word12: 0,
        ptr16_word0: 0,
        ptr16_word4: 0,
        ptr16_word8: 0,
        ptr16_word12: 0,
        cmd_ptr: 0,
        cmd_word0: 0,
        cmd_word4: 0,
        cmd_byte8: 0,
        cmd_byte9: 0,
        cmd_word12: 0,
        cmd_word16: 0,
        cmd_word20: 0,
        cmd_word24: 0,
        cmd_byte28: 0,
        cmd_half32: 0,
        cmd_word36: 0,
        cmd_word40: 0,
        scan_start_pre_arg3: [0; SCAN_START_ARG3_BYTES],
        scan_start_post_arg3: [0; SCAN_START_ARG3_BYTES],
        scan_start_pre_op_chan: 0,
        scan_start_post_op_chan: 0,
        scan_start_pre_current_chan: 0,
        scan_start_post_current_chan: 0,
        scan_start_pre_home_chan: 0,
        scan_start_post_home_chan: 0,
        scan_start_pre_scan_word00: 0,
        scan_start_post_scan_word00: 0,
        scan_start_pre_scan_word114: 0,
        scan_start_post_scan_word114: 0,
        scan_start_pre_scan_ptr: 0,
        scan_start_post_scan_ptr: 0,
        scan_start_pre_chm_ptr: 0,
        scan_start_post_chm_ptr: 0,
        scan_start_pre_chm_ptr08: 0,
        scan_start_post_chm_ptr08: 0,
        scan_start_pre_chm_ptr0c: 0,
        scan_start_post_chm_ptr0c: 0,
        scan_get_id_exec_count: 0,
        scan_get_id_last_callback_ptr: 0,
        scan_get_id_last_arg_ptr: 0,
        scan_get_id_op_chan: 0,
        scan_get_id_scan_word114: 0,
    };
}

static NEXT_SLOT: AtomicUsize = AtomicUsize::new(0);
static mut SNAPSHOTS: [Snapshot; SLOT_COUNT] = [Snapshot::ZERO; SLOT_COUNT];

pub(super) fn reset_scan_process_wrap_diag() {
    logging::reset();
}

pub(super) fn log_scan_process_wrap_diag(stage: &str) {
    logging::log(stage);
}
