[package]
name = "esp_radio_nostd_wifi_control"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.88"

[[bin]]
name = "esp_radio_nostd_wifi_control"
harness = false
test = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[profile.dev.package.esp-radio]
opt-level = 3

[profile.dev.package.esp-rtos]
opt-level = 3

[dependencies]
esp-hal = { version = "1.0.0", features = ["esp32", "unstable"] }
esp-rtos = { path = "../../vendor/esp-rtos-0.2.0", default-features = false, features = ["esp32", "esp-radio", "esp-alloc"] }
esp-radio = { path = "../../vendor/esp-radio-0.17.0", default-features = false, features = ["esp32", "wifi", "sniffer", "esp-alloc", "log-04", "unstable"] }
esp-wifi-sys = "0.8.1"
esp-alloc = { version = "0.9.0", default-features = false, features = ["compat", "esp32"] }
esp-println = { version = "0.16.1", default-features = false, features = ["esp32", "log-04", "uart"] }
esp-backtrace = { version = "0.18.1", default-features = false, features = ["esp32", "panic-handler", "println"] }
log = "0.4"
