[package]
name = "esp_wifi_legacy_nostd_control"
version = "0.1.0"
edition = "2021"
resolver = "2"
rust-version = "1.88"

[[bin]]
name = "esp_wifi_legacy_nostd_control"
harness = false
test = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[profile.dev.package.esp-wifi]
opt-level = 3

[dependencies]
esp-hal = { version = "1.0.0-rc.0", default-features = false, features = ["esp32", "rt", "unstable"] }
esp-wifi = { version = "0.15.1", default-features = false, features = ["esp32", "wifi", "builtin-scheduler", "esp-alloc", "log-04", "sniffer"] }
esp-wifi-sys = "0.7.1"
esp-sync = { version = "0.1.1", default-features = false, features = ["esp32"] }
esp-alloc = { version = "0.8.0", default-features = false }
esp-println = { version = "0.14.0", default-features = false, features = ["esp32", "log-04", "uart"] }
esp-backtrace = { version = "0.16.0", default-features = false, features = ["esp32", "panic-handler", "println"] }
log = "0.4"
